### PR TITLE
Revert "Create 0000-01-02-ZackConord.md"

### PR DESCRIPTION
**Pull request by ngonz**
Reverts ZackConord/github-slideshow#3

### CODE REVIEW

**Review by ngonz — COMMENTED** [review]
Hey Zack, can you reply to this comment?

**Review by ZackConord — COMMENTED** [review]
Comment

**Review by Moose0621 — APPROVED** [review]
looks good, bringing back the stuff that got wiped out?

**Review by ZackConord — APPROVED** [review]
thanks nick

**Pull request merged**
